# GB28181 管理后台配置

[web_config]
host = "0.0.0.0"
port = 8888
layers = [
    #    [1,"auth"],           # 最内层，最靠近 Handler 请在业务模块实现并注册
    [10,"api_log"],        # 请求日志，包含请求和返回信息的日志
    #    [3,"trace"],          # 链路追踪，包含链路追踪信息的日志
    [100,"compression"],    # 压缩
    [10000,"cors"]   # 允许跨域,最外层,最先接收请求
]

[web_config.spa_apps]
"/admin" = "examples/gb28181_admin/ui/dist"

[gb28181_server_config]
platform_id            = "34020000002000000001"
realm                  = "3402000000"
sip_ip                 = "127.0.0.1"
heartbeat_timeout_secs = 120
enable_auth            = true
auth_password          = "tx123456"

[gb28181_server_config.media]
local_ip       = "127.0.0.1"
rtp_port_start = 30000
rtp_port_end   = 40000

[gb28181_server_config.zlm]
base_url = "http://127.0.0.1:8080"
secret   = "035c73f7-bb6b-4889-a715-d9eb2d1925cc"

[sip_config]
host  = "0.0.0.0"
port  = 5060
transport = "both" #tcp udp both

[log_config]
level     = "debug"
console_output = true
