# tx_di 配置文件示例
# 此文件用于演示从配置文件加载组件配置

[log_config]
level = "debug"             # 日志级别
prefix = "di-axum"          # 日志前缀
dir = "./logs"              # 日志目录
console_output = true       # 控制台输出日志
time_format = "local"       # local / utc
[web_config]
# IPv4 配置
host = "127.0.0.1"
# IPv6 配置（取消注释使用）
# host = "::1"              # IPv6 localhost
# host = "::"               # 监听所有 IPv6 接口
port = 8888
enable_cors = true          # 允许跨域
max_body_size = 10485760    # 10M
timeout_secs = 6            # 请求超时时间
layers = [
#    [1,"auth"],           # 最内层，最靠近 Handler todo 还未实现,请在业务模块实现并注册
    [10,"api_log"],        # 请求日志，包含请求和返回信息的日志
#    [3,"trace"],          # 链路追踪，包含链路追踪信息的日志
    [100,"compression"],    # 压缩
    [10000,"cors"]   # 允许跨域,最外层,最先接收请求
]