# 日志配置
[log_config]
level = "info"
prefix = "dfbja7"
dir = "./logs"
console_output = true
time_format = "local"

# 应用配置
[app_config]
# TCP 服务器配置
tcp_port = 10080
tcp_timeout_secs = 150

# MQTT 配置
mqtt_broker = "192.168.0.90"
mqtt_port = 1883
mqtt_client_id = "dfbja7_transformer"
mqtt_username = ""
mqtt_password = ""
mqtt_topic_prefix = "SENSOR/GAS/SRV000"

# 设备型号传感器配置
[app_config.model.GQB200A7U]
sensors = [
    # 可燃气体 10%LEL 低报点 20%LEL 高报点 
    { name = "EX", unit = "%LEL", min = 0.0, max = 10.0 },
    # 硫化氢 10ppm 低报点 20ppm 高报点
    { name = "H2S", unit = "ppm", min = 0.0, max = 10.0 },
    # 一氧化碳 50ppm 低报点 200ppm 高报点
    { name = "CO", unit = "ppm", min = 0.0, max = 1000.0 },
    # 氧气 低于 19.5% Vol 缺氧  高于 23.5% Vol 富氧
    { name = "O2", unit = "%Vol", min = 19.5, max = 23.5 },
]

[app_config.model.Nano4SP]
sensors = [
    # 可燃气体 10%LEL 低报点 20%LEL 高报点 
    { name = "EX", unit = "%LEL", min = 0.0, max = 10.0 },
    # 硫化氢 10ppm 低报点 20ppm 高报点
    { name = "H2S", unit = "ppm", min = 0.0, max = 10.0 },
    # 一氧化碳 50ppm 低报点 200ppm 高报点
    { name = "CO", unit = "ppm", min = 0.0, max = 1000.0 },
    # 氧气 低于 19.5% Vol 缺氧  高于 23.5% Vol 富氧
    { name = "O2", unit = "%Vol", min = 19.5, max = 23.5 },
]